### ISSUE TITLE
Separate utility constants from actual game settings

### ISSUE THREAD

**Issue by pietrykovsky** [pietrykovsky/python-raycaster#5]
Separate those constants to a new `const.py` module:

- https://github.com/pietrykovsky/python-raycaster/blob/7bd864bc20baac54a61e11e9c2d39b382b7459c5/src/settings.py#L11
- https://github.com/pietrykovsky/python-raycaster/blob/7bd864bc20baac54a61e11e9c2d39b382b7459c5/src/settings.py#L19
- https://github.com/pietrykovsky/python-raycaster/blob/7bd864bc20baac54a61e11e9c2d39b382b7459c5/src/settings.py#L24
- https://github.com/pietrykovsky/python-raycaster/blob/7bd864bc20baac54a61e11e9c2d39b382b7459c5/src/settings.py#L31-L34

**Comment by pietrykovsky** [comment]
https://github.com/pietrykovsky/python-raycaster/blob/7bd864bc20baac54a61e11e9c2d39b382b7459c5/src/settings.py#L33
instead of value `10` we could possibly use `max(Map.rows, Map.cols)`

**Comment by Milosz-cat** [comment]
https://github.com/pietrykovsky/python-raycaster/pull/13
