### ISSUE TITLE
Make minimap responsive

### ISSUE THREAD

**Issue by pietrykovsky** [pietrykovsky/python-raycaster#7]
https://github.com/pietrykovsky/python-raycaster/blob/5222cd8d2eb7075ad074e386147c9927d11c91cd/src/settings.py#L30-L33
The actual minimap works only for the current map. If we change the map, the minimap will be rendered incorrectly.
We would like to make the minimap responsive to all kind of level sizes.

**Comment by Milosz-cat** [comment]
https://github.com/pietrykovsky/python-raycaster/pull/13
